#!/usr/bin/env python3
"""Generate token-tracker.md from tokencost/cost.csv.

Reads per-project config from tokencost/config.json:
  branch_pattern  - regex with one capture group for issue number
                    (default: "issue/(\\d+)")
  output_path     - path relative to repo root for the markdown report
                    (default: "docs/economics/token-tracker.md")
  repo_url        - https URL of the repo; auto-detected from git remote if absent
"""

import csv
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


DEFAULT_BRANCH_PATTERN = r"issue/(\d+)"
DEFAULT_OUTPUT_PATH = "docs/economics/token-tracker.md"

DEFAULT_PREAMBLE = (
    "# Token Tracker\n\n"
    "_Add notes above the Data Table heading — they will be preserved on regeneration._\n"
)
DATA_TABLE_HEADING = "## Data Table\n"
GENERATED_BY = (
    "_Generated by `tokencost/generate_token_tracker.py`. "
    "Notes column is human-editable — avoid `|` characters._\n"
)
TABLE_HEADER = (
    "\n| Branch | Issue | Summary | Total Cost (USD) | Notes |\n"
    "|--------|-------|---------|------------------|-------|\n"
)


def load_config(repo_root: Path) -> dict:
    config_path = repo_root / "tokencost" / "config.json"
    if config_path.exists():
        try:
            return json.loads(config_path.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def branch_to_issue_number(branch: str, pattern: re.Pattern) -> Optional[int]:
    m = pattern.search(branch)
    return int(m.group(1)) if m else None


def aggregate(rows: list[dict]) -> dict:
    """Return {branch: {cost_sum, n_sessions, n_errors}}."""
    result = {}
    for row in rows:
        branch = row.get("git_branch", "").strip() or "(no branch)"
        cost_raw = row.get("total_cost_usd", "").strip()
        is_error = cost_raw.upper() == "ERROR"
        entry = result.setdefault(branch, {"cost_sum": 0.0, "n_sessions": 0, "n_errors": 0})
        entry["n_sessions"] += 1
        if is_error:
            entry["n_errors"] += 1
        else:
            try:
                entry["cost_sum"] += float(cost_raw)
            except ValueError:
                entry["n_errors"] += 1
    return result


def format_cost(cost_sum: float, n_errors: int, n_sessions: int) -> str:
    if n_errors == 0:
        return f"${cost_sum:.2f}"
    if n_errors == n_sessions:
        return "$0.00 (all sessions errored)"
    return f"${cost_sum:.2f} (some sessions errored)"


def parse_repo_url(remote_url: str) -> str:
    remote_url = remote_url.strip()
    m = re.match(r"git@([^:]+):(.+?)(?:\.git)?$", remote_url)
    if m:
        return f"https://{m.group(1)}/{m.group(2)}"
    return re.sub(r"\.git$", "", remote_url)


def get_repo_url() -> str:
    try:
        out = subprocess.check_output(
            ["git", "remote", "get-url", "origin"],
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return parse_repo_url(out)
    except Exception:
        return "https://github.com/unknown/unknown"


def parse_user_preamble(md_text: str) -> str:
    marker = "## Data Table"
    idx = md_text.find(marker)
    if idx == -1:
        return ""
    return md_text[:idx].rstrip()


def parse_existing_md(md_text: str) -> dict:
    """Return {branch: {issue, summary, notes}} from existing md table."""
    result = {}
    in_table = False
    header_seen = False
    for line in md_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("|") and not in_table:
            in_table = True
        if not in_table or not stripped.startswith("|"):
            continue
        if re.match(r"^\|[-| ]+\|$", stripped):
            header_seen = True
            continue
        if not header_seen:
            continue
        parts = stripped.split("|")
        cols = [p.strip() for p in parts[1:-1]]
        if len(cols) < 5:
            print(
                f"warning: unexpected column count ({len(cols)}) in row: {line!r}",
                file=sys.stderr,
            )
            continue
        branch, issue, summary, _cost = cols[0], cols[1], cols[2], cols[3]
        notes = "|".join(cols[4:])
        if len(cols) > 5:
            print(
                f"warning: extra pipes in Notes for branch {branch!r} — joined as-is",
                file=sys.stderr,
            )
        if branch == "**Total**":
            continue
        result[branch] = {"issue": issue, "summary": summary, "notes": notes}
    return result


def emit_md(branch_data: dict, repo_url: str, user_preamble: str = "") -> str:
    total_cost = sum(v["cost_sum"] for v in branch_data.values())
    total_errors = sum(v["n_errors"] for v in branch_data.values())
    total_sessions = sum(v["n_sessions"] for v in branch_data.values())
    total_cell = format_cost(total_cost, total_errors, total_sessions)

    rows_sorted = sorted(branch_data.items(), key=lambda kv: kv[1]["cost_sum"], reverse=True)

    preamble = user_preamble if user_preamble else DEFAULT_PREAMBLE.rstrip()
    lines = [preamble, "\n\n", DATA_TABLE_HEADING, "\n", GENERATED_BY, TABLE_HEADER]
    lines.append(f"| **Total** | — | — | {total_cell} | — |\n")
    for branch, v in rows_sorted:
        issue_val = v.get("issue", "—")
        summary_val = v.get("summary", "—")
        notes_val = v.get("notes", "—")
        cost_cell = format_cost(v["cost_sum"], v["n_errors"], v["n_sessions"])
        lines.append(f"| {branch} | {issue_val} | {summary_val} | {cost_cell} | {notes_val} |\n")

    return "".join(lines)


def fetch_title_gh(issue_num: int, repo_url: str) -> Optional[str]:
    m = re.search(r"github\.com[:/](.+?)(?:\.git)?$", repo_url)
    if not m:
        return None
    repo_path = m.group(1)
    try:
        title = subprocess.check_output(
            ["gh", "issue", "view", str(issue_num), "--repo", repo_path,
             "--json", "title", "-q", ".title"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        return title or None
    except Exception:
        return None


def run(
    csv_path: Path,
    md_path: Path,
    branch_pattern: re.Pattern,
    fetch_title=None,
    get_remote_url=None,
    repo_url_override: Optional[str] = None,
):
    if fetch_title is None:
        fetch_title = fetch_title_gh
    if get_remote_url is None:
        get_remote_url = get_repo_url

    if not csv_path.exists():
        print(f"error: cost.csv not found at {csv_path.resolve()}", file=sys.stderr)
        sys.exit(1)

    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    agg = aggregate(rows)

    existing: dict = {}
    user_preamble = ""
    if md_path.exists():
        md_text = md_path.read_text()
        existing = parse_existing_md(md_text)
        user_preamble = parse_user_preamble(md_text)

    repo_url = repo_url_override if repo_url_override else get_remote_url()

    branch_data = {}
    for branch, stats in agg.items():
        entry = {**stats}
        cached = existing.get(branch, {})
        issue_cached = cached.get("issue", "—")
        summary_cached = cached.get("summary", "—")
        notes_cached = cached.get("notes", "—")

        issue_num = branch_to_issue_number(branch, branch_pattern)

        needs_fetch = (
            issue_num is not None
            and (summary_cached in ("—", "(title unavailable)") or issue_cached == "—")
        )

        if needs_fetch:
            title = fetch_title(issue_num, repo_url)
            if title:
                issue_val = f"[#{issue_num}]({repo_url}/issues/{issue_num})"
                summary_val = title
            else:
                issue_val = f"[#{issue_num}]({repo_url}/issues/{issue_num})"
                summary_val = "(title unavailable)"
                print(
                    f"warning: could not fetch title for issue #{issue_num} — "
                    "will retry on next run",
                    file=sys.stderr,
                )
        elif issue_num is not None and issue_cached != "—":
            issue_val = issue_cached
            summary_val = summary_cached
        elif issue_num is not None:
            issue_val = f"[#{issue_num}]({repo_url}/issues/{issue_num})"
            summary_val = summary_cached
        else:
            issue_val = "—"
            summary_val = "—"

        entry["issue"] = issue_val
        entry["summary"] = summary_val
        entry["notes"] = notes_cached
        branch_data[branch] = entry

    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(emit_md(branch_data, repo_url, user_preamble))
    print(f"wrote {md_path}")


def main():
    try:
        repo_root = Path(
            subprocess.check_output(
                ["git", "rev-parse", "--show-toplevel"],
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
        )
    except subprocess.CalledProcessError:
        print("error: not inside a git repository", file=sys.stderr)
        sys.exit(1)

    config = load_config(repo_root)
    branch_pattern_str = config.get("branch_pattern", DEFAULT_BRANCH_PATTERN)
    output_path_str = config.get("output_path", DEFAULT_OUTPUT_PATH)
    repo_url_override = config.get("repo_url") or None

    try:
        branch_pattern = re.compile(branch_pattern_str)
    except re.error as e:
        print(f"error: invalid branch_pattern in config.json: {e}", file=sys.stderr)
        sys.exit(1)

    csv_path = repo_root / "tokencost" / "cost.csv"
    md_path = repo_root / output_path_str

    run(csv_path, md_path, branch_pattern, repo_url_override=repo_url_override)


if __name__ == "__main__":
    main()
